package Models;

import java.sql.Date;

public class DMRC_MAE_FACTURA {

    public String ID_NUM_CONTR;
    public String ID_NUM_FACTURA;
    public Date FCH_GENERACION_INFO;
    public Date FCH_FACTURACION;
    public int IMP_FACTURA_INTERESES;
    public int IMP_PAGO_INTERESES_CLIENTE;
    public Date FCH_FIN_PERIODO_PAGO;
    public int FLG_PAGO_TIEMPO;
    public int IMP_A_PAGAR_TOTAL;
    public int IMP_FACTURA_CAPITAL;
    public int IMP_PAGO_CAPITAL_CLIENTE;
    public Date FCH_CARGA_INFO;
    public int IMP_PAGO_MO;
    public int IMP_PAGO_FACTURA_MO;
    public Date FCH_FACTURA_PAGADA;

    public DMRC_MAE_FACTURA(String ID_NUM_CONTR, String ID_NUM_FACTURA, Date FCH_GENERACION_INFO, Date FCH_FACTURACION, int IMP_FACTURA_INTERESES, int IMP_PAGO_INTERESES_CLIENTE, Date FCH_FIN_PERIODO_PAGO, int FLG_PAGO_TIEMPO, int IMP_A_PAGAR_TOTAL, int IMP_FACTURA_CAPITAL, int IMP_PAGO_CAPITAL_CLIENTE, Date FCH_CARGA_INFO, int IMP_PAGO_MO, int IMP_PAGO_FACTURA_MO, Date FCH_FACTURA_PAGADA) {
        this.ID_NUM_CONTR = ID_NUM_CONTR;
        this.ID_NUM_FACTURA = ID_NUM_FACTURA;
        this.FCH_GENERACION_INFO = FCH_GENERACION_INFO;
        this.FCH_FACTURACION = FCH_FACTURACION;
        this.IMP_FACTURA_INTERESES = IMP_FACTURA_INTERESES;
        this.IMP_PAGO_INTERESES_CLIENTE = IMP_PAGO_INTERESES_CLIENTE;
        this.FCH_FIN_PERIODO_PAGO = FCH_FIN_PERIODO_PAGO;
        this.FLG_PAGO_TIEMPO = FLG_PAGO_TIEMPO;
        this.IMP_A_PAGAR_TOTAL = IMP_A_PAGAR_TOTAL;
        this.IMP_FACTURA_CAPITAL = IMP_FACTURA_CAPITAL;
        this.IMP_PAGO_CAPITAL_CLIENTE = IMP_PAGO_CAPITAL_CLIENTE;
        this.FCH_CARGA_INFO = FCH_CARGA_INFO;
        this.IMP_PAGO_MO = IMP_PAGO_MO;
        this.IMP_PAGO_FACTURA_MO = IMP_PAGO_FACTURA_MO;
        this.FCH_FACTURA_PAGADA = FCH_FACTURA_PAGADA;
    }
}
